/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiV1UsersRouteImport } from './routes/api/v1/users'
import { Route as ApiV1SessionsRouteImport } from './routes/api/v1/sessions'
import { Route as ApiV1UsersMeRouteImport } from './routes/api/v1/users/me'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1UsersRoute = ApiV1UsersRouteImport.update({
  id: '/api/v1/users',
  path: '/api/v1/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionsRoute = ApiV1SessionsRouteImport.update({
  id: '/api/v1/sessions',
  path: '/api/v1/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1UsersMeRoute = ApiV1UsersMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiV1UsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/v1/users': typeof ApiV1UsersRouteWithChildren
  '/api/v1/users/me': typeof ApiV1UsersMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/v1/users': typeof ApiV1UsersRouteWithChildren
  '/api/v1/users/me': typeof ApiV1UsersMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/v1/users': typeof ApiV1UsersRouteWithChildren
  '/api/v1/users/me': typeof ApiV1UsersMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/v1/sessions'
    | '/api/v1/users'
    | '/api/v1/users/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/v1/sessions'
    | '/api/v1/users'
    | '/api/v1/users/me'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/v1/sessions'
    | '/api/v1/users'
    | '/api/v1/users/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiV1SessionsRoute: typeof ApiV1SessionsRoute
  ApiV1UsersRoute: typeof ApiV1UsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/users': {
      id: '/api/v1/users'
      path: '/api/v1/users'
      fullPath: '/api/v1/users'
      preLoaderRoute: typeof ApiV1UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sessions': {
      id: '/api/v1/sessions'
      path: '/api/v1/sessions'
      fullPath: '/api/v1/sessions'
      preLoaderRoute: typeof ApiV1SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/users/me': {
      id: '/api/v1/users/me'
      path: '/me'
      fullPath: '/api/v1/users/me'
      preLoaderRoute: typeof ApiV1UsersMeRouteImport
      parentRoute: typeof ApiV1UsersRoute
    }
  }
}

interface ApiV1UsersRouteChildren {
  ApiV1UsersMeRoute: typeof ApiV1UsersMeRoute
}

const ApiV1UsersRouteChildren: ApiV1UsersRouteChildren = {
  ApiV1UsersMeRoute: ApiV1UsersMeRoute,
}

const ApiV1UsersRouteWithChildren = ApiV1UsersRoute._addFileChildren(
  ApiV1UsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiV1SessionsRoute: ApiV1SessionsRoute,
  ApiV1UsersRoute: ApiV1UsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
